/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "elasticsearch_constants.h"

namespace elasticsearch { namespace thrift {

const elasticsearchConstants g_elasticsearch_constants;

elasticsearchConstants::elasticsearchConstants() {
}

}} // namespace

