/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef elasticsearch_CONSTANTS_H
#define elasticsearch_CONSTANTS_H

#include "elasticsearch_types.h"

namespace elasticsearch { namespace thrift {

class elasticsearchConstants {
 public:
  elasticsearchConstants();

};

extern const elasticsearchConstants g_elasticsearch_constants;

}} // namespace

#endif
